// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"inutil/token"
)

const (
	NoState    = -1
	NumStates  = 73
	NumSymbols = 90
)

type Lexer struct {
	src    []byte
	pos    int
	line   int
	column int
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:    src,
		pos:    0,
		line:   1,
		column: 1,
	}
	return lexer
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	return NewLexer(src), nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = new(token.Token)
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: 'v'
1: 'a'
2: 'r'
3: 'f'
4: 'u'
5: 'n'
6: 'c'
7: 's'
8: 't'
9: 'r'
10: 'u'
11: 'c'
12: 't'
13: 't'
14: 'y'
15: 'p'
16: 'e'
17: 'r'
18: 'e'
19: 't'
20: 'u'
21: 'r'
22: 'n'
23: 'i'
24: 'f'
25: 'e'
26: 'l'
27: 's'
28: 'e'
29: 'f'
30: 'o'
31: 'r'
32: '+'
33: '-'
34: '+'
35: '-'
36: '0'
37: '+'
38: '-'
39: 'e'
40: 'm'
41: 'p'
42: 't'
43: 'y'
44: '('
45: ')'
46: '{'
47: '}'
48: ','
49: ';'
50: '='
51: '&'
52: '&'
53: '|'
54: '|'
55: '<'
56: '='
57: '>'
58: '='
59: '!'
60: '='
61: '='
62: '='
63: '<'
64: '>'
65: '/'
66: '*'
67: '+'
68: '-'
69: '_'
70: '/'
71: '/'
72: '\n'
73: '/'
74: '*'
75: '*'
76: '*'
77: '/'
78: '0'
79: '.'
80: '\t'
81: '\n'
82: '\r'
83: ' '
84: '1'-'9'
85: 'A'-'Z'
86: 'a'-'z'
87: '0'-'9'
88: '1'-'9'
89: .
*/
